# -*- coding: utf-8 -*-
"""featureimpinfo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DNRzKEMyRcROvILkXz8f_A_Plh_Z48nu
"""

import spacy

# Load spaCy's pre-trained English model
nlp = spacy.load("en_core_web_sm")

def extract_information(text):
    # Process the text with spaCy
    doc = nlp(text)

    # Extract relevant information
    entities = []
    for ent in doc.ents:
        entities.append({
            'text': ent.text,
            'start': ent.start_char,
            'end': ent.end_char,
            'label': ent.label_
        })

    return entities

# Example text document
sample_text = """
John Doe lives in New York. He works at XYZ Corporation.
Jane Smith is visiting Paris next week for a conference.
"""

result = extract_information(sample_text)
print(result)